---
- name: create web launch script
  template:
    src: concourse-web.j2
    dest: "{{ concourse_web_launcher_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_web_launcher_mode }}"
    force: yes
  become: yes
  notify:
  - restart concourse web

- name: create web service
  template:
    src: concourse-web.service.j2
    dest: /etc/systemd/system/concourse-web.service
    owner: root
    force: yes
  become: yes
  register: concourse_web_service
  notify:
  - restart concourse web
  - systemd daemon reload
  tags:
  - no-test
