---
- hosts: default
  remote_user: root
  roles:
  - role: ./
    concourse_web: yes
    concourse_session_signing_key: "{{ lookup('file', 'spec/default/fixtures/session_signing_key') }}"
    concourse_host_key: "{{ lookup('file', 'spec/default/fixtures/host_key') }}"
    concourse_authorized_worker_keys:
    - "{{ lookup('file', 'spec/default/fixtures/worker_key.pub') }}"
    concourse_external_url: "http://192.168.66.10:8080/"
    concourse_postgres_database: atc
    concourse_postgres_user: concourse
    concourse_postgres_password: concourse
    concourse_postgres_host: localhost
    concourse_local_users:
    - name: "admin"
      password: "$2y$12$zC93VotYq3cCwTTEZ/2o6uZA8VLITcdzoDbmfYH4ofMf1l1NRlal2" # admin
    concourse_main_team_local_users:
    - admin
  - role: ./
    concourse_worker: yes
    concourse_tsa_host: "localhost:2222"
    concourse_tsa_public_key: "{{ lookup('file', 'spec/default/fixtures/host_key.pub') }}"
    concourse_tsa_worker_key: "{{ lookup('file', 'spec/default/fixtures/worker_key') }}"
